markdown: kramdown
highlighter: pygments
permalink: blog/:year/:month/:day/:title.html
paginate: 6
paginate_path: page/:num

blog:
    name: kidy's bolg                                               # 博客名称
    description: 有机会我把我的故事讲给你听                                        # 博客描述
    title: 爱旅行的程序狗小文青                                              # 网页标题
    url:                                                 # 博客地址
    duoshuo:                                             # 多说ID
    tongji:                                              # 百度统计ID
    qiniu:                                               # 七牛云地址
author:
    name:  kidy                                              # 作者名称
    email:  zjindiss@gmail.com                                            # 邮箱地址
    weibo:  zjindiss@gmail.com                                           # 微博地址
    github: https://github.com/z-kidy                                             # GitHub地址
    logo:  /img/hanhan.jpg  # logo地址
    douban:
        name:                                            # 豆瓣地址名称
        key:                                             # 豆瓣API Key
